### ISSUE TITLE
Flow使用时在协程中线程调度切换问题

### ISSUE THREAD

**Issue by lihuiqiang123** [chenxyu/retrofit-adapter-flow#2]
Flow本身可以通过中间操作符 flowOn() 来进行线程切换，不推荐使用 withContext() 来切换线程。

**Comment by chenxyu** [comment]
> Flow本身可以通过中间操作符 flowOn() 来进行线程切换，不推荐使用 withContext() 来切换线程。

现在默认是异步的，代码还不完善，这几天改一下支持同步就可以使用flowOn()
